# Generated by Django 4.2.16 on 2025-01-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0008_alter_transaction_options_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount of money involved in the transaction.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='The account receiving money. Null for withdrawals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='bankingapp.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='The account sending money. Null for deposits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='bankingapp.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer')], help_text='Type of transaction: Deposit, Withdrawal, or Transfer.', max_length=10),
        ),
    ]
